name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: horadoqa/robot:v1
      options: --user root

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      
      - name: Fix permissions
        run: |
          chmod -R 777 /github/workspace

      - name: Listar arquivos (debug opcional)
        run: ls -R

      - name: Executar testes Robot Framework
        run: |
          robot projetos/robot/robot.robot